# This is workflow runs on PR
#
name: Pull Request Target

# Controls when the action will run.
on:
  # Trigger workflow for pull requests.
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-pr:
    name: '▶️ actions'
    uses: ./.github/workflows/lint-pr.yml

  lint-code:
    name: '▶️ actions'
    needs: [lint-pr]
    uses: ./.github/workflows/lint-code.yml

  build-code:
    name: '▶️ actions'
    needs: [lint-code]
    uses: ./.github/workflows/build-code.yml

  test-code:
    name: '▶️ actions'
    needs: [lint-code]
    uses: ./.github/workflows/test-code.yml

  codeql:
    name: '▶️ actions'
    needs: [lint-code]
    uses: ./.github/workflows/codeql.yml

  dependabot:
    name: '▶️ actions'
    uses: ./.github/workflows/dependabot.yml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN  }}
